### ISSUE TITLE
Add phonetic symbol for English and pinyin for Chinese to mark how to read the word

### ISSUE THREAD

**Issue by skyofsimba** [xicri/genshin-dictionary#142]
Would you add phonetic symbol for English and pinyin for Chinese to mark how to read the word ?

There are quite a lot rarely seen chinese characters in this game that people don't know how to read.
And it's the same with English.

**Comment by xicri** [comment]
Hi @skyofsimba, thanks for your feedback, and sorry for my delayed reply.

First, I recently didn't update the Genshin Dictionary because of my health issues and so on, so I don't think I can work on this Issue soon. Sorry :pray:

I need a bit more clarification on your request.

What is your native language? Chinese? English?

There are already pinyin for the rarely-used characters (生僻字) in Chinese. Do you think it is not enough?
![](https://github.com/xicri/genshin-dictionary/assets/107226297/4a96653b-af29-4a81-88e0-5309f5586d74)

For English, we might be able to get phonetic symbols for common nouns from some opensource English dictionary.
However, I don't think I can add them for proprietary nouns such as Chevreuse and Dehya because there are any information sources of phonetic symbols for such words.
I can express the English pronunciations for the proprietary nouns in Katakana, but can't in English phonetic symbols.

**Comment by skyofsimba** [comment]
Thank you for replying and I sincerely hope that you will soon be restored to health. 
First of all I'm a native Chinese speaker. But I want to take the following screenshot as an example. 地灵龛 itself isn't annotated while the entries below are. 
There should be many issues like this. I'm sure I i
have seen a lot. 




​

---- Replied Message ----
| From | ***@***.***> |
| Date | 02/11/2024 23:09 |
| To | xicri/genshin-dictionary ***@***.***> |
| Cc | skyofsimba ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [xicri/genshin-dictionary] Add phonetic symbol for English and pinyin for Chinese to mark how to read the word (Issue #142) |

Hi @skyofsimba, thanks for your feedback, and sorry for my delayed reply.

First, I recently didn't update the Genshin Dictionary because of my health issues and so on, so I don't think I can work on this Issue soon. Sorry

I need a bit more clarification on your request.

What is your native language? Chinese? English?

There are already pinyin for the rarely-used characters (生僻字) in Chinese. Do you think it is not enough?
FuEaXxaacAMXEns.png (view on web)

For English, we might be able to get phonetic symbols for common nouns from some opensource English dictionary.
However, I don't think I can add them for proprietary nouns such as Chevreuse and Dehya because there are any information sources of phonetic symbols for such words.
I can express the English pronunciations for the proprietary nouns in Katakana, but can't in English phonetic symbols.

**Comment by skyofsimba** [comment]
![QQ图片20240214185332](https://github.com/xicri/genshin-dictionary/assets/60432165/353bc2ad-98ae-4a56-8a34-ab7477d8699c)

**Comment by xicri** [comment]
Thanks @skyofsimba, I understand your point.

The pinyin for the rarely-used characters (生僻字) are manually added, so some 生僻字 may be missing.

If you have software engineering background and are motivated to contribute to Genshin Dictionary, you can add them to [the dictionary soure data](https://github.com/xicri/genshin-langdata/tree/main/dataset/dictionary) by yourself.

The dictionary source data is written in JSON5 and you can add pinyin in the following format:

```json5
pinyins: [{ char: "峠", pron: "qia3" }],
```

See the following code as an example:

https://github.com/xicri/genshin-langdata/blob/main/dataset/dictionary/locations.json5#L1033

Feel free to ask me any questions if you have.

> I sincerely hope that you will soon be restored to health.

Thanks!

**Comment by xicri** [comment]
Closing for now.
